import { Toaster } from "@/components/ui/sonner";
import StoreProvider from "@/providers/StoreProvider";
import AppLayoutWrapper from "@/utils/AppLayoutWrapper";
import type { Metadata } from "next";
import { Archivo, Geist } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Archivo({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          {/* <Navbar /> */}
          <AppLayoutWrapper>
            {children}
            <Toaster richColors position="top-center" />
          </AppLayoutWrapper>
          {/* <Footer /> */}
        </StoreProvider>
      </body>
    </html>
  );
}
